## Data Cleaning & Pre-processing
![data-cleaning-in-python](https://daxg39y63pxwu.cloudfront.net/images/blog/data-cleaning-in-python/data-cleaning-in-python.png)

First step of an analytics project is to clean the datasets and pre-processed it to make it suitable for use by analytical model and visualization

In [1]:
# import basic libraries
import pandas as pd
import numpy as np

### 1. Import dataset into the notebook

In [2]:
# heart_pki_original_df -> personal_key_indicators_dataframe
heart_pki_original_df = pd.read_csv('datasets/heart_pki_2020_original.csv')
heart_pki_original_df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [3]:
# heart_attack_df
heart_attack_df = pd.read_csv('datasets/heart_attack_original.csv')
heart_attack_df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

### 2. Data Cleaning & Pre-processing (heart_pki_original_df)

In [4]:
heart_pki_original_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), object(14)
memory usage: 43.9+ MB

#### **2.1 Removing rows with NA values (if they exist)**

In [5]:
print('Number of NA entries: ', heart_pki_original_df.isna().sum().sum())

Number of NA entries:  0

- there are no NA entries, so there are no rows with NA to be dropped :)

#### **2.2 Cleaning up continuous variables**

In [6]:
heart_pki_original_df.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  319795.000000    319795.00000  319795.000000  319795.000000
mean       28.325399         3.37171       3.898366       7.097075
std         6.356100         7.95085       7.955235       1.436007
min        12.020000         0.00000       0.000000       1.000000
25%        24.030000         0.00000       0.000000       6.000000
50%        27.340000         0.00000       0.000000       7.000000
75%        31.420000         2.00000       3.000000       8.000000
max        94.850000        30.00000      30.000000      24.000000

- **`PhysicalHealth`** and **`MentalHealth`** contain '0's.
- Those '0's are valid because of the nature of the variable **(no. of days)**
  - **`PhysicalHealth`**: Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 was your physical health not good
  - **`MentalHealth`**: Thinking about your mental health, for how many days during the past 30 days was your mental health not good?


Conclusion:
- no need to do anything to those '0' values

#### **2.3 Cleaning up categorical variables**

In [7]:
for feature in heart_pki_original_df.columns:
  if np.dtype(heart_pki_original_df[feature]) != 'object':
    continue
  print(heart_pki_original_df[feature].value_counts(), end='\n\n')

No     292422
Yes     27373
Name: HeartDisease, dtype: int64

No     187887
Yes    131908
Name: Smoking, dtype: int64

No     298018
Yes     21777
Name: AlcoholDrinking, dtype: int64

No     307726
Yes     12069
Name: Stroke, dtype: int64

No     275385
Yes     44410
Name: DiffWalking, dtype: int64

Female    167805
Male      151990
Name: Sex, dtype: int64

65-69          34151
60-64          33686
70-74          31065
55-59          29757
50-54          25382
80 or older    24153
45-49          21791
75-79          21482
18-24          21064
40-44          21006
35-39          20550
30-34          18753
25-29          16955
Name: AgeCategory, dtype: int64

White                             245212
Hispanic                           27446
Black                              22939
Other                              10928
Asian                               8068
American Indian/Alaskan Native      5202
Name: Race, dtype: int64

No                         269653
Yes                         40802
No, borderline diabetes      6781
Yes (during pregnancy)       2559
Name: Diabetic, dtype: int64

Yes    247957
No      71838
Name: PhysicalActivity, dtype: int64

Very good    113858
Good          93129
Excellent     66842
Fair          34677
Poor          11289
Name: GenHealth, dtype: int64

No     276923
Yes     42872
Name: Asthma, dtype: int64

No     308016
Yes     11779
Name: KidneyDisease, dtype: int64

No     289976
Yes     29819
Name: SkinCancer, dtype: int64

- all the categorical variables are consistent in their values
- there are no missing values

Therefore, no data cleaning is needed for categorical variables. However, one hot encoding is needed for categorical variables to encode them into numeric forms to allow analytical models to operate on these categorical variables

#### **2.4 Encoding nominal (unordered) categorical variables using `OneHotEncoding`**
The `heart_pki_original_df` dataset contains 14 categorical variables:
- HeartDisease
- Smoking
- AlcoholDrinking
- Stroke
- DiffWalking
- Sex
- AgeCategory
- Race
- Diabetic
- PhysicalActivity
- GenHealth
- Asthma
- Kidney
- Disease

**2.4 a) OneHotEncoding**

In [12]:
# Import the OneHotEncoder from sklearn
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

# OneHotEncoding of categorical predictors
cat_variables = [
    'HeartDisease', 'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking',
    'Sex', 'AgeCategory', 'Race', 'Diabetic', 'PhysicalActivity',
    'GenHealth', 'Asthma', 'KidneyDisease', 'SkinCancer'
]

heart_pki_cat = heart_pki_original_df[cat_variables]

ohe.fit(heart_pki_cat)
heart_pki_cat_ohe = pd.DataFrame(
    ohe.transform(heart_pki_cat).toarray(),
    columns=ohe.get_feature_names_out(heart_pki_cat.columns))

# Check the encoded variables
heart_pki_cat_ohe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 48 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   HeartDisease_No                      319795 non-null  float64
 1   HeartDisease_Yes                     319795 non-null  float64
 2   Smoking_No                           319795 non-null  float64
 3   Smoking_Yes                          319795 non-null  float64
 4   AlcoholDrinking_No                   319795 non-null  float64
 5   AlcoholDrinking_Yes                  319795 non-null  float64
 6   Stroke_No                            319795 non-null  float64
 7   Stroke_Yes                           319795 non-null  float64
 8   DiffWalking_No                       319795 non-null  float64
 9   DiffWalking_Yes                      319795 non-null  float64
 10  Sex_Female                           319795 non-null  float64
 11  Sex_Male                             319795 non-null  float64
 12  AgeCategory_18-24                    319795 non-null  float64
 13  AgeCategory_25-29                    319795 non-null  float64
 14  AgeCategory_30-34                    319795 non-null  float64
 15  AgeCategory_35-39                    319795 non-null  float64
 16  AgeCategory_40-44                    319795 non-null  float64
 17  AgeCategory_45-49                    319795 non-null  float64
 18  AgeCategory_50-54                    319795 non-null  float64
 19  AgeCategory_55-59                    319795 non-null  float64
 20  AgeCategory_60-64                    319795 non-null  float64
 21  AgeCategory_65-69                    319795 non-null  float64
 22  AgeCategory_70-74                    319795 non-null  float64
 23  AgeCategory_75-79                    319795 non-null  float64
 24  AgeCategory_80 or older              319795 non-null  float64
 25  Race_American Indian/Alaskan Native  319795 non-null  float64
 26  Race_Asian                           319795 non-null  float64
 27  Race_Black                           319795 non-null  float64
 28  Race_Hispanic                        319795 non-null  float64
 29  Race_Other                           319795 non-null  float64
 30  Race_White                           319795 non-null  float64
 31  Diabetic_No                          319795 non-null  float64
 32  Diabetic_No, borderline diabetes     319795 non-null  float64
 33  Diabetic_Yes                         319795 non-null  float64
 34  Diabetic_Yes (during pregnancy)      319795 non-null  float64
 35  PhysicalActivity_No                  319795 non-null  float64
 36  PhysicalActivity_Yes                 319795 non-null  float64
 37  GenHealth_Excellent                  319795 non-null  float64
 38  GenHealth_Fair                       319795 non-null  float64
 39  GenHealth_Good                       319795 non-null  float64
 40  GenHealth_Poor                       319795 non-null  float64
 41  GenHealth_Very good                  319795 non-null  float64
 42  Asthma_No                            319795 non-null  float64
 43  Asthma_Yes                           319795 non-null  float64
 44  KidneyDisease_No                     319795 non-null  float64
 45  KidneyDisease_Yes                    319795 non-null  float64
 46  SkinCancer_No                        319795 non-null  float64
 47  SkinCancer_Yes                       319795 non-null  float64
dtypes: float64(48)
memory usage: 117.1 MB

In [13]:
# head of dataframe
heart_pki_cat_ohe.head()

,HeartDisease_No,HeartDisease_Yes,Smoking_No,Smoking_Yes,AlcoholDrinking_No,AlcoholDrinking_Yes,Stroke_No,Stroke_Yes,DiffWalking_No,DiffWalking_Yes,...,GenHealth_Fair,GenHealth_Good,GenHealth_Poor,GenHealth_Very good,Asthma_No,Asthma_Yes,KidneyDisease_No,KidneyDisease_Yes,SkinCancer_No,SkinCancer_Yes
0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
3,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

**2.4 b) Combine encoded dataframe with continuous variables**

In [14]:
num_variable = []
for i in heart_pki_original_df:
    if i not in cat_variables:
        num_variable.append(i)
num_variable

['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime']

In [18]:
# Combining Numeric features with the OHE Categorical features
heart_pki_num = heart_pki_original_df[num_variable]
heart_pki_cat_ohe
heart_pki_ohe_df = pd.concat(
    [heart_pki_num, heart_pki_cat_ohe],
    sort=False,
    axis=1).reindex(index=heart_pki_original_df.index)

# Check the final dataframe
heart_pki_ohe_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 52 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   BMI                                  319795 non-null  float64
 1   PhysicalHealth                       319795 non-null  float64
 2   MentalHealth                         319795 non-null  float64
 3   SleepTime                            319795 non-null  float64
 4   HeartDisease_No                      319795 non-null  float64
 5   HeartDisease_Yes                     319795 non-null  float64
 6   Smoking_No                           319795 non-null  float64
 7   Smoking_Yes                          319795 non-null  float64
 8   AlcoholDrinking_No                   319795 non-null  float64
 9   AlcoholDrinking_Yes                  319795 non-null  float64
 10  Stroke_No                            319795 non-null  float64
 11  Stroke_Yes                           319795 non-null  float64
 12  DiffWalking_No                       319795 non-null  float64
 13  DiffWalking_Yes                      319795 non-null  float64
 14  Sex_Female                           319795 non-null  float64
 15  Sex_Male                             319795 non-null  float64
 16  AgeCategory_18-24                    319795 non-null  float64
 17  AgeCategory_25-29                    319795 non-null  float64
 18  AgeCategory_30-34                    319795 non-null  float64
 19  AgeCategory_35-39                    319795 non-null  float64
 20  AgeCategory_40-44                    319795 non-null  float64
 21  AgeCategory_45-49                    319795 non-null  float64
 22  AgeCategory_50-54                    319795 non-null  float64
 23  AgeCategory_55-59                    319795 non-null  float64
 24  AgeCategory_60-64                    319795 non-null  float64
 25  AgeCategory_65-69                    319795 non-null  float64
 26  AgeCategory_70-74                    319795 non-null  float64
 27  AgeCategory_75-79                    319795 non-null  float64
 28  AgeCategory_80 or older              319795 non-null  float64
 29  Race_American Indian/Alaskan Native  319795 non-null  float64
 30  Race_Asian                           319795 non-null  float64
 31  Race_Black                           319795 non-null  float64
 32  Race_Hispanic                        319795 non-null  float64
 33  Race_Other                           319795 non-null  float64
 34  Race_White                           319795 non-null  float64
 35  Diabetic_No                          319795 non-null  float64
 36  Diabetic_No, borderline diabetes     319795 non-null  float64
 37  Diabetic_Yes                         319795 non-null  float64
 38  Diabetic_Yes (during pregnancy)      319795 non-null  float64
 39  PhysicalActivity_No                  319795 non-null  float64
 40  PhysicalActivity_Yes                 319795 non-null  float64
 41  GenHealth_Excellent                  319795 non-null  float64
 42  GenHealth_Fair                       319795 non-null  float64
 43  GenHealth_Good                       319795 non-null  float64
 44  GenHealth_Poor                       319795 non-null  float64
 45  GenHealth_Very good                  319795 non-null  float64
 46  Asthma_No                            319795 non-null  float64
 47  Asthma_Yes                           319795 non-null  float64
 48  KidneyDisease_No                     319795 non-null  float64
 49  KidneyDisease_Yes                    319795 non-null  float64
 50  SkinCancer_No                        319795 non-null  float64
 51  SkinCancer_Yes                       319795 non-null  float64
dtypes: float64(52)
memory usage: 126.9 MB

In [28]:
# ALL of the columns
for col in heart_pki_ohe_df.columns:
    print(col, end=',  ')

BMI,  PhysicalHealth,  MentalHealth,  SleepTime,  HeartDisease_No,  HeartDisease_Yes,  Smoking_No,  Smoking_Yes,  AlcoholDrinking_No,  AlcoholDrinking_Yes,  Stroke_No,  Stroke_Yes,  DiffWalking_No,  DiffWalking_Yes,  Sex_Female,  Sex_Male,  AgeCategory_18-24,  AgeCategory_25-29,  AgeCategory_30-34,  AgeCategory_35-39,  AgeCategory_40-44,  AgeCategory_45-49,  AgeCategory_50-54,  AgeCategory_55-59,  AgeCategory_60-64,  AgeCategory_65-69,  AgeCategory_70-74,  AgeCategory_75-79,  AgeCategory_80 or older,  Race_American Indian/Alaskan Native,  Race_Asian,  Race_Black,  Race_Hispanic,  Race_Other,  Race_White,  Diabetic_No,  Diabetic_No, borderline diabetes,  Diabetic_Yes,  Diabetic_Yes (during pregnancy),  PhysicalActivity_No,  PhysicalActivity_Yes,  GenHealth_Excellent,  GenHealth_Fair,  GenHealth_Good,  GenHealth_Poor,  GenHealth_Very good,  Asthma_No,  Asthma_Yes,  KidneyDisease_No,  KidneyDisease_Yes,  SkinCancer_No,  SkinCancer_Yes,

In [29]:
heart_pki_ohe_df.head()

,BMI,PhysicalHealth,MentalHealth,SleepTime,HeartDisease_No,HeartDisease_Yes,Smoking_No,Smoking_Yes,AlcoholDrinking_No,AlcoholDrinking_Yes,...,GenHealth_Fair,GenHealth_Good,GenHealth_Poor,GenHealth_Very good,Asthma_No,Asthma_Yes,KidneyDisease_No,KidneyDisease_Yes,SkinCancer_No,SkinCancer_Yes
0,16.60,3.0,30.0,5.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
1,20.34,0.0,0.0,7.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2,26.58,20.0,30.0,8.0,1.0,0.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
3,24.21,0.0,0.0,6.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,23.71,28.0,0.0,8.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

**2.4 c) Export encoded `heart_pki_ohe_df` dataframe as csv**

In [30]:
heart_pki_ohe_df.to_csv('datasets/heart_pki_2020_encoded.csv')

#### **2.5 Export cleaned dataset**

In [31]:
# since the dataset is already very cleaned, the exported csv will be the same as the original csv
heart_pki_original_df.to_csv('datasets/heart_pki_2020_cleaned.csv')

### 3. Data Cleaning and Pre-processing (heart_attack_df)

In [32]:
heart_attack_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB